#这些是支持的资金模型平台

GitHub:#替换为最多4个支持GitHub赞助商的用户名，例如[user1，user2]
帕特雷翁:#替换为单个Patreon用户名
打开集合(_C):#替换为单个Open Collective用户名
Ko_fi:#替换为单个Ko-fi用户名
潮汐漂移:#替换为单个Tidelift平台-名称/包-名称，例如npm/babel
community_bridge:#替换为单个社区桥项目-名称，例如Cloud-Foundry
利伯拉佩:#替换为单个Liberapay用户名
问题搜寻:#替换为单个IssueHunt用户名
otechie:#替换为单个Otechie用户名
LFX_众筹:#替换为单个LFX众筹项目-名称，如云铸造
自定义:#替换为最多4个自定义赞助URL，例如['link1'，'link2']
